### ISSUE TITLE
Database Design/Cleaning

### ISSUE THREAD

**Issue by Wikitelmex** [IcaliaLabs/rails-app-quickstart#6]
## Background
We already have an example schema, but we need to define the fields that will really use in the Assessment tool project and create a real-world schema

## Tasks
- [ ] Define tables
- [ ] Define fields
- [ ] Create generic rails project
- [ ] Create migrations/migrate

**Comment by vovimayhem** [comment]
The PR #8 Added a users table. It's a thing for the repos created from this template to implement the database each one will need... Closing this.
